project:
  type: website
  output-dir: docs
  
# ~ additional metadata excluded for brevity ~

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



